Update

diff --git a/Apps/omenfan b/Apps/omenfan
--- a/Apps/omenfan
+++ b/Apps/omenfan
@@ -18,102 +18,102 @@ USER_MODE="1"
 ########################## Functions ################################
 # Helper for calculating
 abs_diff() {
-  local a=$1
-  local b=$2
-  echo $((a > b ? a - b : b - a))
+    local a=$1
+    local b=$2
+    echo $((a > b ? a - b : b - a))
 }
 
 # Change fans mode betweet bios and user
 # Only recieve one argument
 change_mode() {
-  # Get current mode
-  cur_mode=$(ec_probe read $MODE_REGISTER | awk '{print $1}')
+    # Get current mode
+    cur_mode=$(ec_probe read $MODE_REGISTER | awk '{print $1}')
 
-  # Get input mode
-  case "$1" in
-  "bios")
-    input_mode=$BIOS_MODE
-    ;;
-  "user")
-    input_mode=$USER_MODE
-    ;;
-  *)
-    echo "Error: Invaild mode!"
-    exit 1
-    ;;
-  esac
+    # Get input mode
+    case "$1" in
+    "bios")
+        input_mode=$BIOS_MODE
+        ;;
+    "user")
+        input_mode=$USER_MODE
+        ;;
+    *)
+        echo "Error: Invaild mode!"
+        exit 1
+        ;;
+    esac
 
-  # Prevent useless mode change
-  if [[ "$cur_mode" = "$input_mode" ]]; then
-    printf "Fans are already in %s controlled mode.\n" $1
-    exit 1
-  fi
+    # Prevent useless mode change
+    if [[ "$cur_mode" = "$input_mode" ]]; then
+        printf "Fans are already in %s controlled mode.\n" $1
+        exit 1
+    fi
 
-  case "$1" in
-  "bios")
-    # Set fans speed to minimal speed firstly, then switch to bios
-    change_speed $MIN_SPEED
-    ec_probe write "$MODE_REGISTER" $BIOS_MODE
-    # Set fans to invaild state
-    ec_probe write "$FANS_REGISTER" $FANS_INVAILD
-    echo "Switch to BIOS controlled mode."
-    ;;
-  "user")
-    ec_probe write "$MODE_REGISTER" $USER_MODE
-    # Set fans to minimal speed
-    ec_probe write "$FANS_REGISTER" $MIN_SPEED
-    echo "Switch to USER controlled mode."
-    ;;
-  esac
+    case "$1" in
+    "bios")
+        # Set fans speed to minimal speed firstly, then switch to bios
+        change_speed $MIN_SPEED
+        ec_probe write "$MODE_REGISTER" $BIOS_MODE
+        # Set fans to invaild state
+        ec_probe write "$FANS_REGISTER" $FANS_INVAILD
+        echo "Switch to BIOS controlled mode."
+        ;;
+    "user")
+        ec_probe write "$MODE_REGISTER" $USER_MODE
+        # Set fans to minimal speed
+        ec_probe write "$FANS_REGISTER" $MIN_SPEED
+        echo "Switch to USER controlled mode."
+        ;;
+    esac
 }
 
 # Change fans speed
 # Only recieve one argument
 change_speed() {
-  # Check if fans in user mode
-  mode=$(ec_probe read $MODE_REGISTER | awk '{print $1}')
-  if [[ $mode != $USER_MODE ]]; then
-    echo "Fans are not in user controlled mode."
-    exit 1
-  fi
+    # Check if fans in user mode
+    mode=$(ec_probe read $MODE_REGISTER | awk '{print $1}')
+    if [[ $mode != $USER_MODE ]]; then
+        echo "Fans are not in user controlled mode."
+        exit 1
+    fi
 
-  # Check if the input speed is vaild
-  if [[ $1 -lt $MIN_SPEED || $1 -gt $MAX_SPEED ]]; then
-    echo "Error: Invaild input speed."
-    exit 1
-  fi
+    # Check if the input speed is vaild
+    if [[ $1 -lt $MIN_SPEED || $1 -gt $MAX_SPEED ]]; then
+        echo "Error: Invaild input speed."
+        exit 1
+    fi
 
-  # Let the fans speed change slowly to expend fans life time
-  former_speed=$(ec_probe read $FANS_REGISTER | awk '{print $1}')
-  latter_speed=$1
-  cur_speed=$former_speed
-  increment=$(abs_diff former_speed latter_speed)
-  echo "Changing speed......"
-  for ((i = 0; i < increment; i++)); do
-    cur_speed=$((former_speed > latter_speed ? cur_speed - 1 : cur_speed + 1))
-    speed_hex=$(printf "0x%x\n" $cur_speed)
-    # printf $(printf '\\x%x' $1) | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x19)) count=1 conv=notrunc
-    # printf '\x01' | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x15)) count=1 conv=notrunc
-    ec_probe write $FANS_REGISTER $speed_hex
-    sleep $TIME_GAP
-  done
+    # Let the fans speed change slowly to expend fans life time
+    former_speed=$(ec_probe read $FANS_REGISTER | awk '{print $1}')
+    latter_speed=$1
+    cur_speed=$former_speed
+    increment=$(abs_diff former_speed latter_speed)
+    echo "Changing speed......"
+    for ((i = 0; i < increment; i++)); do
+        cur_speed=$((former_speed > latter_speed ? cur_speed - 1 : cur_speed + 1))
+        speed_hex=$(printf "0x%x\n" $cur_speed)
+        # printf $(printf '\\x%x' $1) | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x19)) count=1 conv=notrunc
+        # printf '\x01' | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x15)) count=1 conv=notrunc
+        ec_probe write $FANS_REGISTER $speed_hex
+        sleep $TIME_GAP
+    done
 
-  printf "Set fans speed to %d00 RPM.\n" $1
+    printf "Set fans speed to %d00 RPM.\n" $1
 }
 
 ############################# Body ###########################
 
 # Check if you are root
-if [ $(whoami) != "root" ]; then
-  echo "ERROR: This script must be run as root."
-  exit 1
+if [ "$EUID" -ne 0 ]; then
+    echo "ERROR: This script must be run as root."
+    exit 1
 fi
 
 # Check arguments
 if [[ $# -ne 2 ]]; then
-  echo "Usage: omenfan mode  <bios/user>"
-  echo "       omenfan speed <speed>"
-  exit 1
+    echo "Usage: omenfan mode  <bios/user>"
+    echo "       omenfan speed <speed>"
+    exit 1
 fi
 
 # Load the ec_sys module with write support
@@ -126,13 +126,13 @@ argument=$2
 # Main
 case "$subcommand" in
 "mode")
-  change_mode $argument
-  ;;
+    change_mode $argument
+    ;;
 "speed")
-  change_speed $argument
-  ;;
+    change_speed $argument
+    ;;
 *)
-  echo "Error: Invaild subcommand."
-  exit 1
-  ;;
+    echo "Error: Invaild subcommand."
+    exit 1
+    ;;
 esac
